
theme: minima

siteConfig:
  title: Bithiah's Homepage
  author: Bithiah Koshy a.k.a vintagemind
  description: My blog where I will be sharing my thoughts. I will be discussing topics on economics, programming, ornithology, and much more.  This is Bithiah's tiny house floating on the World Wide Web. 

themeConfig:
  nav:
    - text: Home
      link: /
    - text: About
      link: /about.html
  social:
    twitter: vintagemind07
    github: vintagemind

    
plugins:
  - resolve: saber-plugin-query-posts
  - resolve: saber-plugin-feed





